

###### NLP SETTINGS
APP_NAME_KEY = "NLP_APP_NAME"
LANG_MODEL_NAME_KEY = "NLP_LANG_MODEL_NAME"
LANG_FIELDS_KEY = "NLP_LANG_FIELS"
WORD_MODEL_NAME_KEY = "NLP_WORD_MODEL_NAME"
WORD_FIELDS_KEY = "NLP_WORD_FIELS"
DEFINITION_MODEL_NAME_KEY = "NLP_DEFINITION_MODEL_NAME"
DEFINITION_FIELDS_KEY = "NLP_DEFINITION_FIELS"
REQUIRED_SETTINGS = [APP_NAME_KEY, LANG_MODEL_NAME_KEY, WORD_MODEL_NAME_KEY, DEFINITION_MODEL_NAME_KEY, LANG_FIELDS_KEY, WORD_FIELDS_KEY, DEFINITION_FIELDS_KEY]

Langage = None
Word = None
Definition = None